version: "3.4"
services:
  postgres:
      image: postgres:9.3-alpine

      volumes:
        - "/data/docker/postgres:/var/lib/postgresql/data:rw"

      environment:
        POSTGRES_USER: "{{ postgres_user }}"
        POSTGRES_PASSWORD: "{{ postgres_passwd }}"

        POSTGRES_DB: "{{ postgres_database }}"

      networks:
          studentenportal-dev:
            aliases:
              - database

      # TODO: Add SysLog logging service

      deploy:
        mode: replicated
        replicas: 1

        restart_policy:
          condition: on-failure
          delay: 1s
          max_attempts: 5
          window: 20s

        resources:
          limits:
            cpus: "0.25"
            memory: "1G"
          reservations:
            cpus: "0.125"
            memory: "750M"

    # TODO: Add application server
    # TODO: Add front-end proxy
    # TODO: Add phpMyAdmin

networks:
  database-net:
    driver: bridge
    internal: true

  proxy-net:
    driver: bridge
    internal: true