- name: Allow everything and enable UFW
  ufw:
    state: enabled
    policy: allow

- name: Deny incomming policy
  ufw:
    direction: incomming
    policy: deny

- ufw:
    rule: allow
    name: OpenSSH

- ufw:
    rule: limit
    port: ssh
    proto: tcp

- name: Allow all access to http ports
  ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  with_items:
    - 80
    - 443
