- name: Install ufw
  apt:
      pkg: ufw
      update-cache: yes
      cache_valid_time: 3600

- name: Allow everything and enable UFW
  ufw:
    state: enabled
    policy: allow

- name: Deny incomming policy
  ufw:
    direction: incoming
    policy: deny

- ufw:
    rule: allow
    name: OpenSSH

- ufw:
    rule: limit
    port: ssh
    proto: tcp

- name: Allow access to http ports
  ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  with_items:
    - 80
    - 443
