#!/usr/bin/env bash

# Forces colors on the output pane
export ANSIBLE_FORCE_COLOR=true

echo 'Name of script-file to execute: '
read script

# Execute playbook
time /home/matt/.local/bin/ansible-playbook ./${script}.yaml ${1} --vault-id @prompt --vault-password-file ./secrets.yaml

# If there is a retry file generated by ansible, remove it, because senseless with one server
if [ -e ./*.retry ]; then
    rm ./*.retry
fi