# Copyright (C)  2018 Matt Baumann
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

---
- name: Executes docker compose on server
  hosts: "<<< host here >>>"
  remote_user: "<<< host username >>>"
  vars:
    STACK_FILE: "production.yaml"

  tasks:
  - name: Include password file
    import_vars: secrets.yaml

  - name: Copy resources to the server
    import_role: name=copy
    vars:
      src: "files/resources"
      dest: "/data/docker"
      owner: "{{ ansible_user_id }}"
      group: "{{ ansible_user_id }}"
      mode: "0600"

  - name: Copy stack file to the server
    import_role: name=copy
    vars:
       src: 'files/docker'

  - name: Execute docker stack on stack-file
    command: "docker stack -c {{ tmpfolder }}/{{ STACK_FILE }}"

  - name: Remove tmp-folder
    file:
      path: "{{ tmpfolder }}"
      status: absent