---
- name: ensure packages are installed
  apt:
    name: "{{ packages }}"
    state: present
    cache_valid_time: "{{ apt_cache_time | int }}"
  vars:
    packages:
      - fail2ban

- name: ensure fail2ban is running
  service:
    name: fail2ban
    state: started
