---

- name: Install packages needed for ansible.
  apt: pkg={{ item }} update-cache=yes cache_valid_time=3600
  with_items:
    - python
    - python-apt
    - python-pycurl
    - python-psycopg2

- name: Install system utilities
  apt: pkg={{ item }} update-cache=yes cache_valid_time=3600
  with_items:
    - git
    - mlocate
    - vim-nox
    - curl
    - dnsutils
