---
- name: ensure that unattended-upgrade packages are installed
  apt:
    name: "{{ packages }}"
    state: present
    cache_valid_time: "{{ apt_cache_time | int }}"
  vars:
    packages:
      - unattended-upgrades
      - update-notifier-common

- name: ensure apt config {{ item.src }} exists
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  loop:
    - { src: "auto-upgrades", dest: "/etc/apt/apt.conf.d/20auto-upgrades" }
    - {
        src: "unattended-upgrades",
        dest: "/etc/apt/apt.conf.d/50unattended-upgrades",
      }
