---
- name: Install unattended-upgrade packages
  apt:
      name: "{{ item }}"
      state:  present
      update-cache: yes
      cache_valid_time: 3600
  loop:
    - unattended-upgrades
    - update-notifier-common

- name: Create APT {{ item.src }} configuration
  copy:
    src: {{ item.src }}
    dest: {{ item.dest }}
    owner: root
    group: root
    mode: 0644
  loop:
    - {src: "auto-upgrades", dest: "/etc/apt/apt.conf.d/20auto-upgrades"}
    - {src: "unattended-upgrades", dest: "/etc/apt/apt.conf.d/50unattended-upgrades"}